[phases.setup]
nixPkgs = ["nodejs", "python311", "python311Packages.pip", "sqlite"]

[phases.build]
cmds = [
  "npm install",
  "python -m pip install -r requirements.txt"
]

[phases.start]
cmd = "gunicorn --bind 0.0.0.0:$PORT wsgi:app"