[phases.setup]
nixPkgs = ["nodejs", "python39", "pip"]

[phases.build]
cmds = ["cd client && npm install && npm run build"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn --bind 0.0.0.0:8000 wsgi:app"