services:
  - type: web
    name: alaqsa-hrm
    env: python
    buildCommand: "cd client && npm install && npm run build && cd .. && pip install -r requirements.txt"
    startCommand: "gunicorn wsgi:app"
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 8000
      - key: SECRET_KEY
        fromGroup: production-secrets
      - key: DATABASE_URL
        fromGroup: production-secrets
      - key: GOOGLE_MAPS_API_KEY
        fromGroup: production-secrets
      - key: COMPANY_NAME
        value: Al-Aqsa Security
      - key: COMPANY_TAGLINE
        value: HR & Payroll Management System
      - key: SESSION_COOKIE_SECURE
        value: true
      - key: SESSION_COOKIE_HTTPONLY
        value: true
      - key: SESSION_COOKIE_SAMESITE
        value: Lax
      - key: SESSION_TIMEOUT
        value: 86400

envVarGroups:
  - name: production-secrets
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false