# Render Configuration for AlAqsaHRM - Updated 2025-05-10
services:
- type: web
  name: AlAqsaHRM
  runtime: python
  repo: https://github.com/arshiyaazim/AlAqsaHRM
  plan: free
  envVars:
  - key: EMAIL_FOR_RESET
    sync: false
  - key: ADMIN_PASSWORD
    sync: false
  - key: ADMIN_USERNAME
    sync: false
  - key: DATABASE_URL
    sync: false
  - key: SECRET_KEY
    sync: false
  - key: FLASK_ENV
    value: production
  - key: SESSION_SECRET
    generateValue: true
  - key: JWT_SECRET
    generateValue: true
  region: oregon
  buildCommand: >
    pip install -r requirements.txt && 
    if [ ! -d "exports" ]; then mkdir exports; fi && 
    if [ ! -d "logs" ]; then mkdir logs; fi
  preDeployCommand: >
    python -c "import os, sqlite3; 
    os.makedirs('instance', exist_ok=True); 
    if not os.path.exists('instance/attendance.db'): 
      from app import init_db, app; 
      with app.app_context(): 
        init_db(); 
        print('Database initialized successfully')"
  startCommand: python app.py
  healthCheckPath: /
  envVarsFile: .env.render
version: "1"
