# Exported from Render on 2025-05-10T12:02:53Z
services:
- type: web
  name: AlAqsaHRM
  runtime: python
  repo: https://github.com/arshiyaazim/AlAqsaHRM
  plan: free
  envVars:
  - key: EMAIL_FOR_RESET
    sync: false
  - key: ADMIN_PASSWORD
    sync: false
  - key: ADMIN_USERNAME
    sync: false
  - key: DATABASE_URL
    sync: false
  - key: SECRET_KEY
    sync: false
  - key: FLASK_ENV
    sync: false
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: python app.py
version: "1"
